// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.protoc

package com.adebski;

public final class ExampleProtoc {
  private ExampleProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.adebski.AccountType}
   */
  public enum AccountType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PERSONAL = 0;</code>
     */
    PERSONAL(0),
    /**
     * <code>PROFESSIONAL = 1;</code>
     */
    PROFESSIONAL(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PERSONAL = 0;</code>
     */
    public static final int PERSONAL_VALUE = 0;
    /**
     * <code>PROFESSIONAL = 1;</code>
     */
    public static final int PROFESSIONAL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AccountType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AccountType forNumber(int value) {
      switch (value) {
        case 0: return PERSONAL;
        case 1: return PROFESSIONAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AccountType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AccountType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AccountType>() {
            public AccountType findValueByNumber(int number) {
              return AccountType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.adebski.ExampleProtoc.getDescriptor().getEnumTypes().get(0);
    }

    private static final AccountType[] VALUES = values();

    public static AccountType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AccountType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.adebski.AccountType)
  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.adebski.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string surname = 2;</code>
     * @return The surname.
     */
    java.lang.String getSurname();
    /**
     * <code>string surname = 2;</code>
     * @return The bytes for surname.
     */
    com.google.protobuf.ByteString
        getSurnameBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <pre>
     * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
     * type or our custom type.
     * </pre>
     *
     * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
     */
    java.util.List<com.adebski.ExampleProtoc.AccountDetails> 
        getAccountsList();
    /**
     * <pre>
     * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
     * type or our custom type.
     * </pre>
     *
     * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
     */
    com.adebski.ExampleProtoc.AccountDetails getAccounts(int index);
    /**
     * <pre>
     * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
     * type or our custom type.
     * </pre>
     *
     * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
     */
    int getAccountsCount();
    /**
     * <pre>
     * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
     * type or our custom type.
     * </pre>
     *
     * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
     */
    java.util.List<? extends com.adebski.ExampleProtoc.AccountDetailsOrBuilder> 
        getAccountsOrBuilderList();
    /**
     * <pre>
     * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
     * type or our custom type.
     * </pre>
     *
     * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
     */
    com.adebski.ExampleProtoc.AccountDetailsOrBuilder getAccountsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * message keyword defines a data type that we want to model, inside we define the fields present in a Person data type.
   * Protocol Buffers require that each field has type, name, and a numeric identifier used during serialization and
   * deserialization. In the compact message format the serialized message does not contain field names, only identifiers
   * in order to reduce the message size.
   * </pre>
   *
   * Protobuf type {@code com.adebski.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.adebski.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      surname_ = "";
      email_ = "";
      accounts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              surname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                accounts_ = new java.util.ArrayList<com.adebski.ExampleProtoc.AccountDetails>();
                mutable_bitField0_ |= 0x00000001;
              }
              accounts_.add(
                  input.readMessage(com.adebski.ExampleProtoc.AccountDetails.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          accounts_ = java.util.Collections.unmodifiableList(accounts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adebski.ExampleProtoc.internal_static_com_adebski_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adebski.ExampleProtoc.internal_static_com_adebski_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adebski.ExampleProtoc.Person.class, com.adebski.ExampleProtoc.Person.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SURNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object surname_;
    /**
     * <code>string surname = 2;</code>
     * @return The surname.
     */
    @java.lang.Override
    public java.lang.String getSurname() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        surname_ = s;
        return s;
      }
    }
    /**
     * <code>string surname = 2;</code>
     * @return The bytes for surname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSurnameBytes() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        surname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTS_FIELD_NUMBER = 4;
    private java.util.List<com.adebski.ExampleProtoc.AccountDetails> accounts_;
    /**
     * <pre>
     * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
     * type or our custom type.
     * </pre>
     *
     * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.adebski.ExampleProtoc.AccountDetails> getAccountsList() {
      return accounts_;
    }
    /**
     * <pre>
     * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
     * type or our custom type.
     * </pre>
     *
     * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.adebski.ExampleProtoc.AccountDetailsOrBuilder> 
        getAccountsOrBuilderList() {
      return accounts_;
    }
    /**
     * <pre>
     * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
     * type or our custom type.
     * </pre>
     *
     * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
     */
    @java.lang.Override
    public int getAccountsCount() {
      return accounts_.size();
    }
    /**
     * <pre>
     * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
     * type or our custom type.
     * </pre>
     *
     * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
     */
    @java.lang.Override
    public com.adebski.ExampleProtoc.AccountDetails getAccounts(int index) {
      return accounts_.get(index);
    }
    /**
     * <pre>
     * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
     * type or our custom type.
     * </pre>
     *
     * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
     */
    @java.lang.Override
    public com.adebski.ExampleProtoc.AccountDetailsOrBuilder getAccountsOrBuilder(
        int index) {
      return accounts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getSurnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, surname_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      for (int i = 0; i < accounts_.size(); i++) {
        output.writeMessage(4, accounts_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getSurnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, surname_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      for (int i = 0; i < accounts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, accounts_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adebski.ExampleProtoc.Person)) {
        return super.equals(obj);
      }
      com.adebski.ExampleProtoc.Person other = (com.adebski.ExampleProtoc.Person) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getSurname()
          .equals(other.getSurname())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getAccountsList()
          .equals(other.getAccountsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SURNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSurname().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getAccountsCount() > 0) {
        hash = (37 * hash) + ACCOUNTS_FIELD_NUMBER;
        hash = (53 * hash) + getAccountsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adebski.ExampleProtoc.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExampleProtoc.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExampleProtoc.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExampleProtoc.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExampleProtoc.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExampleProtoc.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExampleProtoc.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.ExampleProtoc.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.ExampleProtoc.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adebski.ExampleProtoc.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.ExampleProtoc.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.ExampleProtoc.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adebski.ExampleProtoc.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * message keyword defines a data type that we want to model, inside we define the fields present in a Person data type.
     * Protocol Buffers require that each field has type, name, and a numeric identifier used during serialization and
     * deserialization. In the compact message format the serialized message does not contain field names, only identifiers
     * in order to reduce the message size.
     * </pre>
     *
     * Protobuf type {@code com.adebski.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.adebski.Person)
        com.adebski.ExampleProtoc.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adebski.ExampleProtoc.internal_static_com_adebski_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adebski.ExampleProtoc.internal_static_com_adebski_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adebski.ExampleProtoc.Person.class, com.adebski.ExampleProtoc.Person.Builder.class);
      }

      // Construct using com.adebski.ExampleProtoc.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAccountsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        surname_ = "";

        email_ = "";

        if (accountsBuilder_ == null) {
          accounts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          accountsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adebski.ExampleProtoc.internal_static_com_adebski_Person_descriptor;
      }

      @java.lang.Override
      public com.adebski.ExampleProtoc.Person getDefaultInstanceForType() {
        return com.adebski.ExampleProtoc.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.adebski.ExampleProtoc.Person build() {
        com.adebski.ExampleProtoc.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.adebski.ExampleProtoc.Person buildPartial() {
        com.adebski.ExampleProtoc.Person result = new com.adebski.ExampleProtoc.Person(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.surname_ = surname_;
        result.email_ = email_;
        if (accountsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            accounts_ = java.util.Collections.unmodifiableList(accounts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.accounts_ = accounts_;
        } else {
          result.accounts_ = accountsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adebski.ExampleProtoc.Person) {
          return mergeFrom((com.adebski.ExampleProtoc.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adebski.ExampleProtoc.Person other) {
        if (other == com.adebski.ExampleProtoc.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getSurname().isEmpty()) {
          surname_ = other.surname_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (accountsBuilder_ == null) {
          if (!other.accounts_.isEmpty()) {
            if (accounts_.isEmpty()) {
              accounts_ = other.accounts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAccountsIsMutable();
              accounts_.addAll(other.accounts_);
            }
            onChanged();
          }
        } else {
          if (!other.accounts_.isEmpty()) {
            if (accountsBuilder_.isEmpty()) {
              accountsBuilder_.dispose();
              accountsBuilder_ = null;
              accounts_ = other.accounts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              accountsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAccountsFieldBuilder() : null;
            } else {
              accountsBuilder_.addAllMessages(other.accounts_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adebski.ExampleProtoc.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adebski.ExampleProtoc.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object surname_ = "";
      /**
       * <code>string surname = 2;</code>
       * @return The surname.
       */
      public java.lang.String getSurname() {
        java.lang.Object ref = surname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          surname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string surname = 2;</code>
       * @return The bytes for surname.
       */
      public com.google.protobuf.ByteString
          getSurnameBytes() {
        java.lang.Object ref = surname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          surname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string surname = 2;</code>
       * @param value The surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        surname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string surname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSurname() {
        
        surname_ = getDefaultInstance().getSurname();
        onChanged();
        return this;
      }
      /**
       * <code>string surname = 2;</code>
       * @param value The bytes for surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        surname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.adebski.ExampleProtoc.AccountDetails> accounts_ =
        java.util.Collections.emptyList();
      private void ensureAccountsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          accounts_ = new java.util.ArrayList<com.adebski.ExampleProtoc.AccountDetails>(accounts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.adebski.ExampleProtoc.AccountDetails, com.adebski.ExampleProtoc.AccountDetails.Builder, com.adebski.ExampleProtoc.AccountDetailsOrBuilder> accountsBuilder_;

      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public java.util.List<com.adebski.ExampleProtoc.AccountDetails> getAccountsList() {
        if (accountsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(accounts_);
        } else {
          return accountsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public int getAccountsCount() {
        if (accountsBuilder_ == null) {
          return accounts_.size();
        } else {
          return accountsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public com.adebski.ExampleProtoc.AccountDetails getAccounts(int index) {
        if (accountsBuilder_ == null) {
          return accounts_.get(index);
        } else {
          return accountsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public Builder setAccounts(
          int index, com.adebski.ExampleProtoc.AccountDetails value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.set(index, value);
          onChanged();
        } else {
          accountsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public Builder setAccounts(
          int index, com.adebski.ExampleProtoc.AccountDetails.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.set(index, builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public Builder addAccounts(com.adebski.ExampleProtoc.AccountDetails value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.add(value);
          onChanged();
        } else {
          accountsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public Builder addAccounts(
          int index, com.adebski.ExampleProtoc.AccountDetails value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.add(index, value);
          onChanged();
        } else {
          accountsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public Builder addAccounts(
          com.adebski.ExampleProtoc.AccountDetails.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.add(builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public Builder addAccounts(
          int index, com.adebski.ExampleProtoc.AccountDetails.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.add(index, builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public Builder addAllAccounts(
          java.lang.Iterable<? extends com.adebski.ExampleProtoc.AccountDetails> values) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, accounts_);
          onChanged();
        } else {
          accountsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public Builder clearAccounts() {
        if (accountsBuilder_ == null) {
          accounts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          accountsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public Builder removeAccounts(int index) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.remove(index);
          onChanged();
        } else {
          accountsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public com.adebski.ExampleProtoc.AccountDetails.Builder getAccountsBuilder(
          int index) {
        return getAccountsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public com.adebski.ExampleProtoc.AccountDetailsOrBuilder getAccountsOrBuilder(
          int index) {
        if (accountsBuilder_ == null) {
          return accounts_.get(index);  } else {
          return accountsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public java.util.List<? extends com.adebski.ExampleProtoc.AccountDetailsOrBuilder> 
           getAccountsOrBuilderList() {
        if (accountsBuilder_ != null) {
          return accountsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(accounts_);
        }
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public com.adebski.ExampleProtoc.AccountDetails.Builder addAccountsBuilder() {
        return getAccountsFieldBuilder().addBuilder(
            com.adebski.ExampleProtoc.AccountDetails.getDefaultInstance());
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public com.adebski.ExampleProtoc.AccountDetails.Builder addAccountsBuilder(
          int index) {
        return getAccountsFieldBuilder().addBuilder(
            index, com.adebski.ExampleProtoc.AccountDetails.getDefaultInstance());
      }
      /**
       * <pre>
       * repeated keyword is used to declare a field holding a sequence of items. We can declare sequences of primitive
       * type or our custom type.
       * </pre>
       *
       * <code>repeated .com.adebski.AccountDetails accounts = 4;</code>
       */
      public java.util.List<com.adebski.ExampleProtoc.AccountDetails.Builder> 
           getAccountsBuilderList() {
        return getAccountsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.adebski.ExampleProtoc.AccountDetails, com.adebski.ExampleProtoc.AccountDetails.Builder, com.adebski.ExampleProtoc.AccountDetailsOrBuilder> 
          getAccountsFieldBuilder() {
        if (accountsBuilder_ == null) {
          accountsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.adebski.ExampleProtoc.AccountDetails, com.adebski.ExampleProtoc.AccountDetails.Builder, com.adebski.ExampleProtoc.AccountDetailsOrBuilder>(
                  accounts_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          accounts_ = null;
        }
        return accountsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.adebski.Person)
    }

    // @@protoc_insertion_point(class_scope:com.adebski.Person)
    private static final com.adebski.ExampleProtoc.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adebski.ExampleProtoc.Person();
    }

    public static com.adebski.ExampleProtoc.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.adebski.ExampleProtoc.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AccountDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.adebski.AccountDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.com.adebski.AccountType accountType = 2;</code>
     * @return The enum numeric value on the wire for accountType.
     */
    int getAccountTypeValue();
    /**
     * <code>.com.adebski.AccountType accountType = 2;</code>
     * @return The accountType.
     */
    com.adebski.ExampleProtoc.AccountType getAccountType();

    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    int getMetadataCount();
    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    boolean containsMetadata(
        java.lang.String key);
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMetadata();
    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMetadataMap();
    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    java.lang.String getMetadataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    java.lang.String getMetadataOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.adebski.AccountDetails}
   */
  public static final class AccountDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.adebski.AccountDetails)
      AccountDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccountDetails.newBuilder() to construct.
    private AccountDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccountDetails() {
      id_ = "";
      accountType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AccountDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AccountDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              accountType_ = rawValue;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                metadata_ = com.google.protobuf.MapField.newMapField(
                    MetadataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metadata__ = input.readMessage(
                  MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              metadata_.getMutableMap().put(
                  metadata__.getKey(), metadata__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adebski.ExampleProtoc.internal_static_com_adebski_AccountDetails_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adebski.ExampleProtoc.internal_static_com_adebski_AccountDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adebski.ExampleProtoc.AccountDetails.class, com.adebski.ExampleProtoc.AccountDetails.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTTYPE_FIELD_NUMBER = 2;
    private int accountType_;
    /**
     * <code>.com.adebski.AccountType accountType = 2;</code>
     * @return The enum numeric value on the wire for accountType.
     */
    @java.lang.Override public int getAccountTypeValue() {
      return accountType_;
    }
    /**
     * <code>.com.adebski.AccountType accountType = 2;</code>
     * @return The accountType.
     */
    @java.lang.Override public com.adebski.ExampleProtoc.AccountType getAccountType() {
      @SuppressWarnings("deprecation")
      com.adebski.ExampleProtoc.AccountType result = com.adebski.ExampleProtoc.AccountType.valueOf(accountType_);
      return result == null ? com.adebski.ExampleProtoc.AccountType.UNRECOGNIZED : result;
    }

    public static final int METADATA_FIELD_NUMBER = 3;
    private static final class MetadataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.adebski.ExampleProtoc.internal_static_com_adebski_AccountDetails_MetadataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metadata_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetadata() {
      if (metadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      return metadata_;
    }

    public int getMetadataCount() {
      return internalGetMetadata().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    @java.lang.Override
    public boolean containsMetadata(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
      return internalGetMetadata().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMetadataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMetadataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (accountType_ != com.adebski.ExampleProtoc.AccountType.PERSONAL.getNumber()) {
        output.writeEnum(2, accountType_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMetadata(),
          MetadataDefaultEntryHolder.defaultEntry,
          3);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (accountType_ != com.adebski.ExampleProtoc.AccountType.PERSONAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, accountType_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMetadata().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, metadata__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adebski.ExampleProtoc.AccountDetails)) {
        return super.equals(obj);
      }
      com.adebski.ExampleProtoc.AccountDetails other = (com.adebski.ExampleProtoc.AccountDetails) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (accountType_ != other.accountType_) return false;
      if (!internalGetMetadata().equals(
          other.internalGetMetadata())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + ACCOUNTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + accountType_;
      if (!internalGetMetadata().getMap().isEmpty()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMetadata().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adebski.ExampleProtoc.AccountDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExampleProtoc.AccountDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExampleProtoc.AccountDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExampleProtoc.AccountDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExampleProtoc.AccountDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExampleProtoc.AccountDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExampleProtoc.AccountDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.ExampleProtoc.AccountDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.ExampleProtoc.AccountDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adebski.ExampleProtoc.AccountDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.ExampleProtoc.AccountDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.ExampleProtoc.AccountDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adebski.ExampleProtoc.AccountDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.adebski.AccountDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.adebski.AccountDetails)
        com.adebski.ExampleProtoc.AccountDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adebski.ExampleProtoc.internal_static_com_adebski_AccountDetails_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adebski.ExampleProtoc.internal_static_com_adebski_AccountDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adebski.ExampleProtoc.AccountDetails.class, com.adebski.ExampleProtoc.AccountDetails.Builder.class);
      }

      // Construct using com.adebski.ExampleProtoc.AccountDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        accountType_ = 0;

        internalGetMutableMetadata().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adebski.ExampleProtoc.internal_static_com_adebski_AccountDetails_descriptor;
      }

      @java.lang.Override
      public com.adebski.ExampleProtoc.AccountDetails getDefaultInstanceForType() {
        return com.adebski.ExampleProtoc.AccountDetails.getDefaultInstance();
      }

      @java.lang.Override
      public com.adebski.ExampleProtoc.AccountDetails build() {
        com.adebski.ExampleProtoc.AccountDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.adebski.ExampleProtoc.AccountDetails buildPartial() {
        com.adebski.ExampleProtoc.AccountDetails result = new com.adebski.ExampleProtoc.AccountDetails(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.accountType_ = accountType_;
        result.metadata_ = internalGetMetadata();
        result.metadata_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adebski.ExampleProtoc.AccountDetails) {
          return mergeFrom((com.adebski.ExampleProtoc.AccountDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adebski.ExampleProtoc.AccountDetails other) {
        if (other == com.adebski.ExampleProtoc.AccountDetails.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.accountType_ != 0) {
          setAccountTypeValue(other.getAccountTypeValue());
        }
        internalGetMutableMetadata().mergeFrom(
            other.internalGetMetadata());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adebski.ExampleProtoc.AccountDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adebski.ExampleProtoc.AccountDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int accountType_ = 0;
      /**
       * <code>.com.adebski.AccountType accountType = 2;</code>
       * @return The enum numeric value on the wire for accountType.
       */
      @java.lang.Override public int getAccountTypeValue() {
        return accountType_;
      }
      /**
       * <code>.com.adebski.AccountType accountType = 2;</code>
       * @param value The enum numeric value on the wire for accountType to set.
       * @return This builder for chaining.
       */
      public Builder setAccountTypeValue(int value) {
        
        accountType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.adebski.AccountType accountType = 2;</code>
       * @return The accountType.
       */
      @java.lang.Override
      public com.adebski.ExampleProtoc.AccountType getAccountType() {
        @SuppressWarnings("deprecation")
        com.adebski.ExampleProtoc.AccountType result = com.adebski.ExampleProtoc.AccountType.valueOf(accountType_);
        return result == null ? com.adebski.ExampleProtoc.AccountType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.adebski.AccountType accountType = 2;</code>
       * @param value The accountType to set.
       * @return This builder for chaining.
       */
      public Builder setAccountType(com.adebski.ExampleProtoc.AccountType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        accountType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.adebski.AccountType accountType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountType() {
        
        accountType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> metadata_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMetadata() {
        if (metadata_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        return metadata_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMetadata() {
        onChanged();;
        if (metadata_ == null) {
          metadata_ = com.google.protobuf.MapField.newMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        if (!metadata_.isMutable()) {
          metadata_ = metadata_.copy();
        }
        return metadata_;
      }

      public int getMetadataCount() {
        return internalGetMetadata().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      @java.lang.Override
      public boolean containsMetadata(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMetadata().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetadataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
        return getMetadataMap();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
        return internalGetMetadata().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getMetadataOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetadata().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getMetadataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetadata().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMetadata() {
        internalGetMutableMetadata().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      public Builder removeMetadata(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetadata().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMetadata() {
        return internalGetMutableMetadata().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */
      public Builder putMetadata(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetadata().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      public Builder putAllMetadata(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMetadata().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.adebski.AccountDetails)
    }

    // @@protoc_insertion_point(class_scope:com.adebski.AccountDetails)
    private static final com.adebski.ExampleProtoc.AccountDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adebski.ExampleProtoc.AccountDetails();
    }

    public static com.adebski.ExampleProtoc.AccountDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountDetails>
        PARSER = new com.google.protobuf.AbstractParser<AccountDetails>() {
      @java.lang.Override
      public AccountDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccountDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AccountDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.adebski.ExampleProtoc.AccountDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adebski_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adebski_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adebski_AccountDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adebski_AccountDetails_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adebski_AccountDetails_MetadataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adebski_AccountDetails_MetadataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016example.protoc\022\013com.adebski\"e\n\006Person\022" +
      "\014\n\004name\030\001 \001(\t\022\017\n\007surname\030\002 \001(\t\022\r\n\005email\030" +
      "\003 \001(\t\022-\n\010accounts\030\004 \003(\0132\033.com.adebski.Ac" +
      "countDetails\"\271\001\n\016AccountDetails\022\n\n\002id\030\001 " +
      "\001(\t\022-\n\013accountType\030\002 \001(\0162\030.com.adebski.A" +
      "ccountType\022;\n\010metadata\030\003 \003(\0132).com.adebs" +
      "ki.AccountDetails.MetadataEntry\032/\n\rMetad" +
      "ataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001" +
      "*-\n\013AccountType\022\014\n\010PERSONAL\020\000\022\020\n\014PROFESS" +
      "IONAL\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_adebski_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_adebski_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adebski_Person_descriptor,
        new java.lang.String[] { "Name", "Surname", "Email", "Accounts", });
    internal_static_com_adebski_AccountDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_adebski_AccountDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adebski_AccountDetails_descriptor,
        new java.lang.String[] { "Id", "AccountType", "Metadata", });
    internal_static_com_adebski_AccountDetails_MetadataEntry_descriptor =
      internal_static_com_adebski_AccountDetails_descriptor.getNestedTypes().get(0);
    internal_static_com_adebski_AccountDetails_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adebski_AccountDetails_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
