// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: executor-service.protoc

package com.adebski;

public final class ExecutorServiceProtoc {
  private ExecutorServiceProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FixedExecutorServiceConfigurationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.adebski.FixedExecutorServiceConfiguration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string namePattern = 1;</code>
     * @return The namePattern.
     */
    java.lang.String getNamePattern();
    /**
     * <code>string namePattern = 1;</code>
     * @return The bytes for namePattern.
     */
    com.google.protobuf.ByteString
        getNamePatternBytes();

    /**
     * <code>int32 numberOfThreads = 2;</code>
     * @return The numberOfThreads.
     */
    int getNumberOfThreads();

    /**
     * <code>bool daemon = 3;</code>
     * @return The daemon.
     */
    boolean getDaemon();
  }
  /**
   * Protobuf type {@code com.adebski.FixedExecutorServiceConfiguration}
   */
  public static final class FixedExecutorServiceConfiguration extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.adebski.FixedExecutorServiceConfiguration)
      FixedExecutorServiceConfigurationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FixedExecutorServiceConfiguration.newBuilder() to construct.
    private FixedExecutorServiceConfiguration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FixedExecutorServiceConfiguration() {
      namePattern_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FixedExecutorServiceConfiguration();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FixedExecutorServiceConfiguration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              namePattern_ = s;
              break;
            }
            case 16: {

              numberOfThreads_ = input.readInt32();
              break;
            }
            case 24: {

              daemon_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adebski.ExecutorServiceProtoc.internal_static_com_adebski_FixedExecutorServiceConfiguration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adebski.ExecutorServiceProtoc.internal_static_com_adebski_FixedExecutorServiceConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.class, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder.class);
    }

    public static final int NAMEPATTERN_FIELD_NUMBER = 1;
    private volatile java.lang.Object namePattern_;
    /**
     * <code>string namePattern = 1;</code>
     * @return The namePattern.
     */
    @java.lang.Override
    public java.lang.String getNamePattern() {
      java.lang.Object ref = namePattern_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namePattern_ = s;
        return s;
      }
    }
    /**
     * <code>string namePattern = 1;</code>
     * @return The bytes for namePattern.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNamePatternBytes() {
      java.lang.Object ref = namePattern_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namePattern_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBEROFTHREADS_FIELD_NUMBER = 2;
    private int numberOfThreads_;
    /**
     * <code>int32 numberOfThreads = 2;</code>
     * @return The numberOfThreads.
     */
    @java.lang.Override
    public int getNumberOfThreads() {
      return numberOfThreads_;
    }

    public static final int DAEMON_FIELD_NUMBER = 3;
    private boolean daemon_;
    /**
     * <code>bool daemon = 3;</code>
     * @return The daemon.
     */
    @java.lang.Override
    public boolean getDaemon() {
      return daemon_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNamePatternBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namePattern_);
      }
      if (numberOfThreads_ != 0) {
        output.writeInt32(2, numberOfThreads_);
      }
      if (daemon_ != false) {
        output.writeBool(3, daemon_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNamePatternBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namePattern_);
      }
      if (numberOfThreads_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numberOfThreads_);
      }
      if (daemon_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, daemon_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration)) {
        return super.equals(obj);
      }
      com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration other = (com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration) obj;

      if (!getNamePattern()
          .equals(other.getNamePattern())) return false;
      if (getNumberOfThreads()
          != other.getNumberOfThreads()) return false;
      if (getDaemon()
          != other.getDaemon()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAMEPATTERN_FIELD_NUMBER;
      hash = (53 * hash) + getNamePattern().hashCode();
      hash = (37 * hash) + NUMBEROFTHREADS_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfThreads();
      hash = (37 * hash) + DAEMON_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDaemon());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.adebski.FixedExecutorServiceConfiguration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.adebski.FixedExecutorServiceConfiguration)
        com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adebski.ExecutorServiceProtoc.internal_static_com_adebski_FixedExecutorServiceConfiguration_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adebski.ExecutorServiceProtoc.internal_static_com_adebski_FixedExecutorServiceConfiguration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.class, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder.class);
      }

      // Construct using com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        namePattern_ = "";

        numberOfThreads_ = 0;

        daemon_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adebski.ExecutorServiceProtoc.internal_static_com_adebski_FixedExecutorServiceConfiguration_descriptor;
      }

      @java.lang.Override
      public com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration getDefaultInstanceForType() {
        return com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.getDefaultInstance();
      }

      @java.lang.Override
      public com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration build() {
        com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration buildPartial() {
        com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration result = new com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration(this);
        result.namePattern_ = namePattern_;
        result.numberOfThreads_ = numberOfThreads_;
        result.daemon_ = daemon_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration) {
          return mergeFrom((com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration other) {
        if (other == com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.getDefaultInstance()) return this;
        if (!other.getNamePattern().isEmpty()) {
          namePattern_ = other.namePattern_;
          onChanged();
        }
        if (other.getNumberOfThreads() != 0) {
          setNumberOfThreads(other.getNumberOfThreads());
        }
        if (other.getDaemon() != false) {
          setDaemon(other.getDaemon());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object namePattern_ = "";
      /**
       * <code>string namePattern = 1;</code>
       * @return The namePattern.
       */
      public java.lang.String getNamePattern() {
        java.lang.Object ref = namePattern_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          namePattern_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string namePattern = 1;</code>
       * @return The bytes for namePattern.
       */
      public com.google.protobuf.ByteString
          getNamePatternBytes() {
        java.lang.Object ref = namePattern_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          namePattern_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string namePattern = 1;</code>
       * @param value The namePattern to set.
       * @return This builder for chaining.
       */
      public Builder setNamePattern(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namePattern_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string namePattern = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNamePattern() {
        
        namePattern_ = getDefaultInstance().getNamePattern();
        onChanged();
        return this;
      }
      /**
       * <code>string namePattern = 1;</code>
       * @param value The bytes for namePattern to set.
       * @return This builder for chaining.
       */
      public Builder setNamePatternBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namePattern_ = value;
        onChanged();
        return this;
      }

      private int numberOfThreads_ ;
      /**
       * <code>int32 numberOfThreads = 2;</code>
       * @return The numberOfThreads.
       */
      @java.lang.Override
      public int getNumberOfThreads() {
        return numberOfThreads_;
      }
      /**
       * <code>int32 numberOfThreads = 2;</code>
       * @param value The numberOfThreads to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfThreads(int value) {
        
        numberOfThreads_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numberOfThreads = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberOfThreads() {
        
        numberOfThreads_ = 0;
        onChanged();
        return this;
      }

      private boolean daemon_ ;
      /**
       * <code>bool daemon = 3;</code>
       * @return The daemon.
       */
      @java.lang.Override
      public boolean getDaemon() {
        return daemon_;
      }
      /**
       * <code>bool daemon = 3;</code>
       * @param value The daemon to set.
       * @return This builder for chaining.
       */
      public Builder setDaemon(boolean value) {
        
        daemon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool daemon = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDaemon() {
        
        daemon_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.adebski.FixedExecutorServiceConfiguration)
    }

    // @@protoc_insertion_point(class_scope:com.adebski.FixedExecutorServiceConfiguration)
    private static final com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration();
    }

    public static com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FixedExecutorServiceConfiguration>
        PARSER = new com.google.protobuf.AbstractParser<FixedExecutorServiceConfiguration>() {
      @java.lang.Override
      public FixedExecutorServiceConfiguration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FixedExecutorServiceConfiguration(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FixedExecutorServiceConfiguration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FixedExecutorServiceConfiguration> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExecutorServicesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.adebski.ExecutorServices)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
     */
    java.util.List<com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration> 
        getExecutorServiceConfigurationsList();
    /**
     * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
     */
    com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration getExecutorServiceConfigurations(int index);
    /**
     * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
     */
    int getExecutorServiceConfigurationsCount();
    /**
     * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
     */
    java.util.List<? extends com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfigurationOrBuilder> 
        getExecutorServiceConfigurationsOrBuilderList();
    /**
     * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
     */
    com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfigurationOrBuilder getExecutorServiceConfigurationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.adebski.ExecutorServices}
   */
  public static final class ExecutorServices extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.adebski.ExecutorServices)
      ExecutorServicesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExecutorServices.newBuilder() to construct.
    private ExecutorServices(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExecutorServices() {
      executorServiceConfigurations_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExecutorServices();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExecutorServices(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                executorServiceConfigurations_ = new java.util.ArrayList<com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration>();
                mutable_bitField0_ |= 0x00000001;
              }
              executorServiceConfigurations_.add(
                  input.readMessage(com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          executorServiceConfigurations_ = java.util.Collections.unmodifiableList(executorServiceConfigurations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adebski.ExecutorServiceProtoc.internal_static_com_adebski_ExecutorServices_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adebski.ExecutorServiceProtoc.internal_static_com_adebski_ExecutorServices_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adebski.ExecutorServiceProtoc.ExecutorServices.class, com.adebski.ExecutorServiceProtoc.ExecutorServices.Builder.class);
    }

    public static final int EXECUTORSERVICECONFIGURATIONS_FIELD_NUMBER = 1;
    private java.util.List<com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration> executorServiceConfigurations_;
    /**
     * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration> getExecutorServiceConfigurationsList() {
      return executorServiceConfigurations_;
    }
    /**
     * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfigurationOrBuilder> 
        getExecutorServiceConfigurationsOrBuilderList() {
      return executorServiceConfigurations_;
    }
    /**
     * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
     */
    @java.lang.Override
    public int getExecutorServiceConfigurationsCount() {
      return executorServiceConfigurations_.size();
    }
    /**
     * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
     */
    @java.lang.Override
    public com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration getExecutorServiceConfigurations(int index) {
      return executorServiceConfigurations_.get(index);
    }
    /**
     * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
     */
    @java.lang.Override
    public com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfigurationOrBuilder getExecutorServiceConfigurationsOrBuilder(
        int index) {
      return executorServiceConfigurations_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < executorServiceConfigurations_.size(); i++) {
        output.writeMessage(1, executorServiceConfigurations_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < executorServiceConfigurations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, executorServiceConfigurations_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adebski.ExecutorServiceProtoc.ExecutorServices)) {
        return super.equals(obj);
      }
      com.adebski.ExecutorServiceProtoc.ExecutorServices other = (com.adebski.ExecutorServiceProtoc.ExecutorServices) obj;

      if (!getExecutorServiceConfigurationsList()
          .equals(other.getExecutorServiceConfigurationsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getExecutorServiceConfigurationsCount() > 0) {
        hash = (37 * hash) + EXECUTORSERVICECONFIGURATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getExecutorServiceConfigurationsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.ExecutorServiceProtoc.ExecutorServices parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adebski.ExecutorServiceProtoc.ExecutorServices prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.adebski.ExecutorServices}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.adebski.ExecutorServices)
        com.adebski.ExecutorServiceProtoc.ExecutorServicesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adebski.ExecutorServiceProtoc.internal_static_com_adebski_ExecutorServices_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adebski.ExecutorServiceProtoc.internal_static_com_adebski_ExecutorServices_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adebski.ExecutorServiceProtoc.ExecutorServices.class, com.adebski.ExecutorServiceProtoc.ExecutorServices.Builder.class);
      }

      // Construct using com.adebski.ExecutorServiceProtoc.ExecutorServices.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getExecutorServiceConfigurationsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (executorServiceConfigurationsBuilder_ == null) {
          executorServiceConfigurations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          executorServiceConfigurationsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adebski.ExecutorServiceProtoc.internal_static_com_adebski_ExecutorServices_descriptor;
      }

      @java.lang.Override
      public com.adebski.ExecutorServiceProtoc.ExecutorServices getDefaultInstanceForType() {
        return com.adebski.ExecutorServiceProtoc.ExecutorServices.getDefaultInstance();
      }

      @java.lang.Override
      public com.adebski.ExecutorServiceProtoc.ExecutorServices build() {
        com.adebski.ExecutorServiceProtoc.ExecutorServices result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.adebski.ExecutorServiceProtoc.ExecutorServices buildPartial() {
        com.adebski.ExecutorServiceProtoc.ExecutorServices result = new com.adebski.ExecutorServiceProtoc.ExecutorServices(this);
        int from_bitField0_ = bitField0_;
        if (executorServiceConfigurationsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            executorServiceConfigurations_ = java.util.Collections.unmodifiableList(executorServiceConfigurations_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.executorServiceConfigurations_ = executorServiceConfigurations_;
        } else {
          result.executorServiceConfigurations_ = executorServiceConfigurationsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adebski.ExecutorServiceProtoc.ExecutorServices) {
          return mergeFrom((com.adebski.ExecutorServiceProtoc.ExecutorServices)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adebski.ExecutorServiceProtoc.ExecutorServices other) {
        if (other == com.adebski.ExecutorServiceProtoc.ExecutorServices.getDefaultInstance()) return this;
        if (executorServiceConfigurationsBuilder_ == null) {
          if (!other.executorServiceConfigurations_.isEmpty()) {
            if (executorServiceConfigurations_.isEmpty()) {
              executorServiceConfigurations_ = other.executorServiceConfigurations_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureExecutorServiceConfigurationsIsMutable();
              executorServiceConfigurations_.addAll(other.executorServiceConfigurations_);
            }
            onChanged();
          }
        } else {
          if (!other.executorServiceConfigurations_.isEmpty()) {
            if (executorServiceConfigurationsBuilder_.isEmpty()) {
              executorServiceConfigurationsBuilder_.dispose();
              executorServiceConfigurationsBuilder_ = null;
              executorServiceConfigurations_ = other.executorServiceConfigurations_;
              bitField0_ = (bitField0_ & ~0x00000001);
              executorServiceConfigurationsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getExecutorServiceConfigurationsFieldBuilder() : null;
            } else {
              executorServiceConfigurationsBuilder_.addAllMessages(other.executorServiceConfigurations_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adebski.ExecutorServiceProtoc.ExecutorServices parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adebski.ExecutorServiceProtoc.ExecutorServices) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration> executorServiceConfigurations_ =
        java.util.Collections.emptyList();
      private void ensureExecutorServiceConfigurationsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          executorServiceConfigurations_ = new java.util.ArrayList<com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration>(executorServiceConfigurations_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfigurationOrBuilder> executorServiceConfigurationsBuilder_;

      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public java.util.List<com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration> getExecutorServiceConfigurationsList() {
        if (executorServiceConfigurationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(executorServiceConfigurations_);
        } else {
          return executorServiceConfigurationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public int getExecutorServiceConfigurationsCount() {
        if (executorServiceConfigurationsBuilder_ == null) {
          return executorServiceConfigurations_.size();
        } else {
          return executorServiceConfigurationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration getExecutorServiceConfigurations(int index) {
        if (executorServiceConfigurationsBuilder_ == null) {
          return executorServiceConfigurations_.get(index);
        } else {
          return executorServiceConfigurationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public Builder setExecutorServiceConfigurations(
          int index, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration value) {
        if (executorServiceConfigurationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExecutorServiceConfigurationsIsMutable();
          executorServiceConfigurations_.set(index, value);
          onChanged();
        } else {
          executorServiceConfigurationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public Builder setExecutorServiceConfigurations(
          int index, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder builderForValue) {
        if (executorServiceConfigurationsBuilder_ == null) {
          ensureExecutorServiceConfigurationsIsMutable();
          executorServiceConfigurations_.set(index, builderForValue.build());
          onChanged();
        } else {
          executorServiceConfigurationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public Builder addExecutorServiceConfigurations(com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration value) {
        if (executorServiceConfigurationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExecutorServiceConfigurationsIsMutable();
          executorServiceConfigurations_.add(value);
          onChanged();
        } else {
          executorServiceConfigurationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public Builder addExecutorServiceConfigurations(
          int index, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration value) {
        if (executorServiceConfigurationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExecutorServiceConfigurationsIsMutable();
          executorServiceConfigurations_.add(index, value);
          onChanged();
        } else {
          executorServiceConfigurationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public Builder addExecutorServiceConfigurations(
          com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder builderForValue) {
        if (executorServiceConfigurationsBuilder_ == null) {
          ensureExecutorServiceConfigurationsIsMutable();
          executorServiceConfigurations_.add(builderForValue.build());
          onChanged();
        } else {
          executorServiceConfigurationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public Builder addExecutorServiceConfigurations(
          int index, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder builderForValue) {
        if (executorServiceConfigurationsBuilder_ == null) {
          ensureExecutorServiceConfigurationsIsMutable();
          executorServiceConfigurations_.add(index, builderForValue.build());
          onChanged();
        } else {
          executorServiceConfigurationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public Builder addAllExecutorServiceConfigurations(
          java.lang.Iterable<? extends com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration> values) {
        if (executorServiceConfigurationsBuilder_ == null) {
          ensureExecutorServiceConfigurationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, executorServiceConfigurations_);
          onChanged();
        } else {
          executorServiceConfigurationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public Builder clearExecutorServiceConfigurations() {
        if (executorServiceConfigurationsBuilder_ == null) {
          executorServiceConfigurations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          executorServiceConfigurationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public Builder removeExecutorServiceConfigurations(int index) {
        if (executorServiceConfigurationsBuilder_ == null) {
          ensureExecutorServiceConfigurationsIsMutable();
          executorServiceConfigurations_.remove(index);
          onChanged();
        } else {
          executorServiceConfigurationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder getExecutorServiceConfigurationsBuilder(
          int index) {
        return getExecutorServiceConfigurationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfigurationOrBuilder getExecutorServiceConfigurationsOrBuilder(
          int index) {
        if (executorServiceConfigurationsBuilder_ == null) {
          return executorServiceConfigurations_.get(index);  } else {
          return executorServiceConfigurationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public java.util.List<? extends com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfigurationOrBuilder> 
           getExecutorServiceConfigurationsOrBuilderList() {
        if (executorServiceConfigurationsBuilder_ != null) {
          return executorServiceConfigurationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(executorServiceConfigurations_);
        }
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder addExecutorServiceConfigurationsBuilder() {
        return getExecutorServiceConfigurationsFieldBuilder().addBuilder(
            com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.getDefaultInstance());
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder addExecutorServiceConfigurationsBuilder(
          int index) {
        return getExecutorServiceConfigurationsFieldBuilder().addBuilder(
            index, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.getDefaultInstance());
      }
      /**
       * <code>repeated .com.adebski.FixedExecutorServiceConfiguration executorServiceConfigurations = 1;</code>
       */
      public java.util.List<com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder> 
           getExecutorServiceConfigurationsBuilderList() {
        return getExecutorServiceConfigurationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfigurationOrBuilder> 
          getExecutorServiceConfigurationsFieldBuilder() {
        if (executorServiceConfigurationsBuilder_ == null) {
          executorServiceConfigurationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfiguration.Builder, com.adebski.ExecutorServiceProtoc.FixedExecutorServiceConfigurationOrBuilder>(
                  executorServiceConfigurations_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          executorServiceConfigurations_ = null;
        }
        return executorServiceConfigurationsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.adebski.ExecutorServices)
    }

    // @@protoc_insertion_point(class_scope:com.adebski.ExecutorServices)
    private static final com.adebski.ExecutorServiceProtoc.ExecutorServices DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adebski.ExecutorServiceProtoc.ExecutorServices();
    }

    public static com.adebski.ExecutorServiceProtoc.ExecutorServices getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExecutorServices>
        PARSER = new com.google.protobuf.AbstractParser<ExecutorServices>() {
      @java.lang.Override
      public ExecutorServices parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExecutorServices(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExecutorServices> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExecutorServices> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.adebski.ExecutorServiceProtoc.ExecutorServices getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adebski_FixedExecutorServiceConfiguration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adebski_FixedExecutorServiceConfiguration_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adebski_ExecutorServices_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adebski_ExecutorServices_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027executor-service.protoc\022\013com.adebski\"a" +
      "\n!FixedExecutorServiceConfiguration\022\023\n\013n" +
      "amePattern\030\001 \001(\t\022\027\n\017numberOfThreads\030\002 \001(" +
      "\005\022\016\n\006daemon\030\003 \001(\010\"i\n\020ExecutorServices\022U\n" +
      "\035executorServiceConfigurations\030\001 \003(\0132..c" +
      "om.adebski.FixedExecutorServiceConfigura" +
      "tionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_adebski_FixedExecutorServiceConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_adebski_FixedExecutorServiceConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adebski_FixedExecutorServiceConfiguration_descriptor,
        new java.lang.String[] { "NamePattern", "NumberOfThreads", "Daemon", });
    internal_static_com_adebski_ExecutorServices_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_adebski_ExecutorServices_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adebski_ExecutorServices_descriptor,
        new java.lang.String[] { "ExecutorServiceConfigurations", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
