// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key-value.protoc

package com.adebski;

public final class KeyValueProtoc {
  private KeyValueProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ValueWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.adebski.ValueWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stringValue = 1;</code>
     * @return The stringValue.
     */
    java.lang.String getStringValue();
    /**
     * <code>string stringValue = 1;</code>
     * @return The bytes for stringValue.
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>int32 intValue = 2;</code>
     * @return The intValue.
     */
    int getIntValue();

    /**
     * <code>bool boolValue = 3;</code>
     * @return The boolValue.
     */
    boolean getBoolValue();

    /**
     * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
     * @return Whether the nestedConfiguration field is set.
     */
    boolean hasNestedConfiguration();
    /**
     * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
     * @return The nestedConfiguration.
     */
    com.adebski.KeyValueProtoc.GenericConfiguration getNestedConfiguration();
    /**
     * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
     */
    com.adebski.KeyValueProtoc.GenericConfigurationOrBuilder getNestedConfigurationOrBuilder();

    public com.adebski.KeyValueProtoc.ValueWrapper.ValueOneofCase getValueOneofCase();
  }
  /**
   * Protobuf type {@code com.adebski.ValueWrapper}
   */
  public static final class ValueWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.adebski.ValueWrapper)
      ValueWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValueWrapper.newBuilder() to construct.
    private ValueWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValueWrapper() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ValueWrapper();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ValueWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              valueOneofCase_ = 1;
              valueOneof_ = s;
              break;
            }
            case 16: {
              valueOneofCase_ = 2;
              valueOneof_ = input.readInt32();
              break;
            }
            case 24: {
              valueOneofCase_ = 3;
              valueOneof_ = input.readBool();
              break;
            }
            case 34: {
              com.adebski.KeyValueProtoc.GenericConfiguration.Builder subBuilder = null;
              if (valueOneofCase_ == 4) {
                subBuilder = ((com.adebski.KeyValueProtoc.GenericConfiguration) valueOneof_).toBuilder();
              }
              valueOneof_ =
                  input.readMessage(com.adebski.KeyValueProtoc.GenericConfiguration.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.adebski.KeyValueProtoc.GenericConfiguration) valueOneof_);
                valueOneof_ = subBuilder.buildPartial();
              }
              valueOneofCase_ = 4;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adebski.KeyValueProtoc.internal_static_com_adebski_ValueWrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adebski.KeyValueProtoc.internal_static_com_adebski_ValueWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adebski.KeyValueProtoc.ValueWrapper.class, com.adebski.KeyValueProtoc.ValueWrapper.Builder.class);
    }

    private int valueOneofCase_ = 0;
    private java.lang.Object valueOneof_;
    public enum ValueOneofCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      STRINGVALUE(1),
      INTVALUE(2),
      BOOLVALUE(3),
      NESTEDCONFIGURATION(4),
      VALUEONEOF_NOT_SET(0);
      private final int value;
      private ValueOneofCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueOneofCase forNumber(int value) {
        switch (value) {
          case 1: return STRINGVALUE;
          case 2: return INTVALUE;
          case 3: return BOOLVALUE;
          case 4: return NESTEDCONFIGURATION;
          case 0: return VALUEONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueOneofCase
    getValueOneofCase() {
      return ValueOneofCase.forNumber(
          valueOneofCase_);
    }

    public static final int STRINGVALUE_FIELD_NUMBER = 1;
    /**
     * <code>string stringValue = 1;</code>
     * @return The stringValue.
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = "";
      if (valueOneofCase_ == 1) {
        ref = valueOneof_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueOneofCase_ == 1) {
          valueOneof_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string stringValue = 1;</code>
     * @return The bytes for stringValue.
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = "";
      if (valueOneofCase_ == 1) {
        ref = valueOneof_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueOneofCase_ == 1) {
          valueOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTVALUE_FIELD_NUMBER = 2;
    /**
     * <code>int32 intValue = 2;</code>
     * @return The intValue.
     */
    @java.lang.Override
    public int getIntValue() {
      if (valueOneofCase_ == 2) {
        return (java.lang.Integer) valueOneof_;
      }
      return 0;
    }

    public static final int BOOLVALUE_FIELD_NUMBER = 3;
    /**
     * <code>bool boolValue = 3;</code>
     * @return The boolValue.
     */
    @java.lang.Override
    public boolean getBoolValue() {
      if (valueOneofCase_ == 3) {
        return (java.lang.Boolean) valueOneof_;
      }
      return false;
    }

    public static final int NESTEDCONFIGURATION_FIELD_NUMBER = 4;
    /**
     * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
     * @return Whether the nestedConfiguration field is set.
     */
    @java.lang.Override
    public boolean hasNestedConfiguration() {
      return valueOneofCase_ == 4;
    }
    /**
     * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
     * @return The nestedConfiguration.
     */
    @java.lang.Override
    public com.adebski.KeyValueProtoc.GenericConfiguration getNestedConfiguration() {
      if (valueOneofCase_ == 4) {
         return (com.adebski.KeyValueProtoc.GenericConfiguration) valueOneof_;
      }
      return com.adebski.KeyValueProtoc.GenericConfiguration.getDefaultInstance();
    }
    /**
     * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
     */
    @java.lang.Override
    public com.adebski.KeyValueProtoc.GenericConfigurationOrBuilder getNestedConfigurationOrBuilder() {
      if (valueOneofCase_ == 4) {
         return (com.adebski.KeyValueProtoc.GenericConfiguration) valueOneof_;
      }
      return com.adebski.KeyValueProtoc.GenericConfiguration.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (valueOneofCase_ == 1) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, valueOneof_);
      }
      if (valueOneofCase_ == 2) {
        output.writeInt32(
            2, (int)((java.lang.Integer) valueOneof_));
      }
      if (valueOneofCase_ == 3) {
        output.writeBool(
            3, (boolean)((java.lang.Boolean) valueOneof_));
      }
      if (valueOneofCase_ == 4) {
        output.writeMessage(4, (com.adebski.KeyValueProtoc.GenericConfiguration) valueOneof_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (valueOneofCase_ == 1) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, valueOneof_);
      }
      if (valueOneofCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              2, (int)((java.lang.Integer) valueOneof_));
      }
      if (valueOneofCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              3, (boolean)((java.lang.Boolean) valueOneof_));
      }
      if (valueOneofCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (com.adebski.KeyValueProtoc.GenericConfiguration) valueOneof_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adebski.KeyValueProtoc.ValueWrapper)) {
        return super.equals(obj);
      }
      com.adebski.KeyValueProtoc.ValueWrapper other = (com.adebski.KeyValueProtoc.ValueWrapper) obj;

      if (!getValueOneofCase().equals(other.getValueOneofCase())) return false;
      switch (valueOneofCase_) {
        case 1:
          if (!getStringValue()
              .equals(other.getStringValue())) return false;
          break;
        case 2:
          if (getIntValue()
              != other.getIntValue()) return false;
          break;
        case 3:
          if (getBoolValue()
              != other.getBoolValue()) return false;
          break;
        case 4:
          if (!getNestedConfiguration()
              .equals(other.getNestedConfiguration())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (valueOneofCase_) {
        case 1:
          hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
          hash = (53 * hash) + getStringValue().hashCode();
          break;
        case 2:
          hash = (37 * hash) + INTVALUE_FIELD_NUMBER;
          hash = (53 * hash) + getIntValue();
          break;
        case 3:
          hash = (37 * hash) + BOOLVALUE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getBoolValue());
          break;
        case 4:
          hash = (37 * hash) + NESTEDCONFIGURATION_FIELD_NUMBER;
          hash = (53 * hash) + getNestedConfiguration().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adebski.KeyValueProtoc.ValueWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.KeyValueProtoc.ValueWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.ValueWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.KeyValueProtoc.ValueWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.ValueWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.KeyValueProtoc.ValueWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.ValueWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.KeyValueProtoc.ValueWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.ValueWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adebski.KeyValueProtoc.ValueWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.ValueWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.KeyValueProtoc.ValueWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adebski.KeyValueProtoc.ValueWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.adebski.ValueWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.adebski.ValueWrapper)
        com.adebski.KeyValueProtoc.ValueWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adebski.KeyValueProtoc.internal_static_com_adebski_ValueWrapper_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adebski.KeyValueProtoc.internal_static_com_adebski_ValueWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adebski.KeyValueProtoc.ValueWrapper.class, com.adebski.KeyValueProtoc.ValueWrapper.Builder.class);
      }

      // Construct using com.adebski.KeyValueProtoc.ValueWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        valueOneofCase_ = 0;
        valueOneof_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adebski.KeyValueProtoc.internal_static_com_adebski_ValueWrapper_descriptor;
      }

      @java.lang.Override
      public com.adebski.KeyValueProtoc.ValueWrapper getDefaultInstanceForType() {
        return com.adebski.KeyValueProtoc.ValueWrapper.getDefaultInstance();
      }

      @java.lang.Override
      public com.adebski.KeyValueProtoc.ValueWrapper build() {
        com.adebski.KeyValueProtoc.ValueWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.adebski.KeyValueProtoc.ValueWrapper buildPartial() {
        com.adebski.KeyValueProtoc.ValueWrapper result = new com.adebski.KeyValueProtoc.ValueWrapper(this);
        if (valueOneofCase_ == 1) {
          result.valueOneof_ = valueOneof_;
        }
        if (valueOneofCase_ == 2) {
          result.valueOneof_ = valueOneof_;
        }
        if (valueOneofCase_ == 3) {
          result.valueOneof_ = valueOneof_;
        }
        if (valueOneofCase_ == 4) {
          if (nestedConfigurationBuilder_ == null) {
            result.valueOneof_ = valueOneof_;
          } else {
            result.valueOneof_ = nestedConfigurationBuilder_.build();
          }
        }
        result.valueOneofCase_ = valueOneofCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adebski.KeyValueProtoc.ValueWrapper) {
          return mergeFrom((com.adebski.KeyValueProtoc.ValueWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adebski.KeyValueProtoc.ValueWrapper other) {
        if (other == com.adebski.KeyValueProtoc.ValueWrapper.getDefaultInstance()) return this;
        switch (other.getValueOneofCase()) {
          case STRINGVALUE: {
            valueOneofCase_ = 1;
            valueOneof_ = other.valueOneof_;
            onChanged();
            break;
          }
          case INTVALUE: {
            setIntValue(other.getIntValue());
            break;
          }
          case BOOLVALUE: {
            setBoolValue(other.getBoolValue());
            break;
          }
          case NESTEDCONFIGURATION: {
            mergeNestedConfiguration(other.getNestedConfiguration());
            break;
          }
          case VALUEONEOF_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adebski.KeyValueProtoc.ValueWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adebski.KeyValueProtoc.ValueWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int valueOneofCase_ = 0;
      private java.lang.Object valueOneof_;
      public ValueOneofCase
          getValueOneofCase() {
        return ValueOneofCase.forNumber(
            valueOneofCase_);
      }

      public Builder clearValueOneof() {
        valueOneofCase_ = 0;
        valueOneof_ = null;
        onChanged();
        return this;
      }


      /**
       * <code>string stringValue = 1;</code>
       * @return The stringValue.
       */
      @java.lang.Override
      public java.lang.String getStringValue() {
        java.lang.Object ref = "";
        if (valueOneofCase_ == 1) {
          ref = valueOneof_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueOneofCase_ == 1) {
            valueOneof_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringValue = 1;</code>
       * @return The bytes for stringValue.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = "";
        if (valueOneofCase_ == 1) {
          ref = valueOneof_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueOneofCase_ == 1) {
            valueOneof_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringValue = 1;</code>
       * @param value The stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueOneofCase_ = 1;
        valueOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stringValue = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringValue() {
        if (valueOneofCase_ == 1) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string stringValue = 1;</code>
       * @param value The bytes for stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        valueOneofCase_ = 1;
        valueOneof_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 intValue = 2;</code>
       * @return The intValue.
       */
      public int getIntValue() {
        if (valueOneofCase_ == 2) {
          return (java.lang.Integer) valueOneof_;
        }
        return 0;
      }
      /**
       * <code>int32 intValue = 2;</code>
       * @param value The intValue to set.
       * @return This builder for chaining.
       */
      public Builder setIntValue(int value) {
        valueOneofCase_ = 2;
        valueOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intValue = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntValue() {
        if (valueOneofCase_ == 2) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>bool boolValue = 3;</code>
       * @return The boolValue.
       */
      public boolean getBoolValue() {
        if (valueOneofCase_ == 3) {
          return (java.lang.Boolean) valueOneof_;
        }
        return false;
      }
      /**
       * <code>bool boolValue = 3;</code>
       * @param value The boolValue to set.
       * @return This builder for chaining.
       */
      public Builder setBoolValue(boolean value) {
        valueOneofCase_ = 3;
        valueOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool boolValue = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolValue() {
        if (valueOneofCase_ == 3) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
          onChanged();
        }
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.adebski.KeyValueProtoc.GenericConfiguration, com.adebski.KeyValueProtoc.GenericConfiguration.Builder, com.adebski.KeyValueProtoc.GenericConfigurationOrBuilder> nestedConfigurationBuilder_;
      /**
       * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
       * @return Whether the nestedConfiguration field is set.
       */
      @java.lang.Override
      public boolean hasNestedConfiguration() {
        return valueOneofCase_ == 4;
      }
      /**
       * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
       * @return The nestedConfiguration.
       */
      @java.lang.Override
      public com.adebski.KeyValueProtoc.GenericConfiguration getNestedConfiguration() {
        if (nestedConfigurationBuilder_ == null) {
          if (valueOneofCase_ == 4) {
            return (com.adebski.KeyValueProtoc.GenericConfiguration) valueOneof_;
          }
          return com.adebski.KeyValueProtoc.GenericConfiguration.getDefaultInstance();
        } else {
          if (valueOneofCase_ == 4) {
            return nestedConfigurationBuilder_.getMessage();
          }
          return com.adebski.KeyValueProtoc.GenericConfiguration.getDefaultInstance();
        }
      }
      /**
       * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
       */
      public Builder setNestedConfiguration(com.adebski.KeyValueProtoc.GenericConfiguration value) {
        if (nestedConfigurationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          valueOneof_ = value;
          onChanged();
        } else {
          nestedConfigurationBuilder_.setMessage(value);
        }
        valueOneofCase_ = 4;
        return this;
      }
      /**
       * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
       */
      public Builder setNestedConfiguration(
          com.adebski.KeyValueProtoc.GenericConfiguration.Builder builderForValue) {
        if (nestedConfigurationBuilder_ == null) {
          valueOneof_ = builderForValue.build();
          onChanged();
        } else {
          nestedConfigurationBuilder_.setMessage(builderForValue.build());
        }
        valueOneofCase_ = 4;
        return this;
      }
      /**
       * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
       */
      public Builder mergeNestedConfiguration(com.adebski.KeyValueProtoc.GenericConfiguration value) {
        if (nestedConfigurationBuilder_ == null) {
          if (valueOneofCase_ == 4 &&
              valueOneof_ != com.adebski.KeyValueProtoc.GenericConfiguration.getDefaultInstance()) {
            valueOneof_ = com.adebski.KeyValueProtoc.GenericConfiguration.newBuilder((com.adebski.KeyValueProtoc.GenericConfiguration) valueOneof_)
                .mergeFrom(value).buildPartial();
          } else {
            valueOneof_ = value;
          }
          onChanged();
        } else {
          if (valueOneofCase_ == 4) {
            nestedConfigurationBuilder_.mergeFrom(value);
          }
          nestedConfigurationBuilder_.setMessage(value);
        }
        valueOneofCase_ = 4;
        return this;
      }
      /**
       * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
       */
      public Builder clearNestedConfiguration() {
        if (nestedConfigurationBuilder_ == null) {
          if (valueOneofCase_ == 4) {
            valueOneofCase_ = 0;
            valueOneof_ = null;
            onChanged();
          }
        } else {
          if (valueOneofCase_ == 4) {
            valueOneofCase_ = 0;
            valueOneof_ = null;
          }
          nestedConfigurationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
       */
      public com.adebski.KeyValueProtoc.GenericConfiguration.Builder getNestedConfigurationBuilder() {
        return getNestedConfigurationFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
       */
      @java.lang.Override
      public com.adebski.KeyValueProtoc.GenericConfigurationOrBuilder getNestedConfigurationOrBuilder() {
        if ((valueOneofCase_ == 4) && (nestedConfigurationBuilder_ != null)) {
          return nestedConfigurationBuilder_.getMessageOrBuilder();
        } else {
          if (valueOneofCase_ == 4) {
            return (com.adebski.KeyValueProtoc.GenericConfiguration) valueOneof_;
          }
          return com.adebski.KeyValueProtoc.GenericConfiguration.getDefaultInstance();
        }
      }
      /**
       * <code>.com.adebski.GenericConfiguration nestedConfiguration = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.adebski.KeyValueProtoc.GenericConfiguration, com.adebski.KeyValueProtoc.GenericConfiguration.Builder, com.adebski.KeyValueProtoc.GenericConfigurationOrBuilder> 
          getNestedConfigurationFieldBuilder() {
        if (nestedConfigurationBuilder_ == null) {
          if (!(valueOneofCase_ == 4)) {
            valueOneof_ = com.adebski.KeyValueProtoc.GenericConfiguration.getDefaultInstance();
          }
          nestedConfigurationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.adebski.KeyValueProtoc.GenericConfiguration, com.adebski.KeyValueProtoc.GenericConfiguration.Builder, com.adebski.KeyValueProtoc.GenericConfigurationOrBuilder>(
                  (com.adebski.KeyValueProtoc.GenericConfiguration) valueOneof_,
                  getParentForChildren(),
                  isClean());
          valueOneof_ = null;
        }
        valueOneofCase_ = 4;
        onChanged();;
        return nestedConfigurationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.adebski.ValueWrapper)
    }

    // @@protoc_insertion_point(class_scope:com.adebski.ValueWrapper)
    private static final com.adebski.KeyValueProtoc.ValueWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adebski.KeyValueProtoc.ValueWrapper();
    }

    public static com.adebski.KeyValueProtoc.ValueWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValueWrapper>
        PARSER = new com.google.protobuf.AbstractParser<ValueWrapper>() {
      @java.lang.Override
      public ValueWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValueWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValueWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValueWrapper> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.adebski.KeyValueProtoc.ValueWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.adebski.Value)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
     */
    java.util.List<com.adebski.KeyValueProtoc.ValueWrapper> 
        getValueWrapperList();
    /**
     * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
     */
    com.adebski.KeyValueProtoc.ValueWrapper getValueWrapper(int index);
    /**
     * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
     */
    int getValueWrapperCount();
    /**
     * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
     */
    java.util.List<? extends com.adebski.KeyValueProtoc.ValueWrapperOrBuilder> 
        getValueWrapperOrBuilderList();
    /**
     * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
     */
    com.adebski.KeyValueProtoc.ValueWrapperOrBuilder getValueWrapperOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.adebski.Value}
   */
  public static final class Value extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.adebski.Value)
      ValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Value.newBuilder() to construct.
    private Value(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Value() {
      valueWrapper_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Value();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Value(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                valueWrapper_ = new java.util.ArrayList<com.adebski.KeyValueProtoc.ValueWrapper>();
                mutable_bitField0_ |= 0x00000001;
              }
              valueWrapper_.add(
                  input.readMessage(com.adebski.KeyValueProtoc.ValueWrapper.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          valueWrapper_ = java.util.Collections.unmodifiableList(valueWrapper_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adebski.KeyValueProtoc.internal_static_com_adebski_Value_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adebski.KeyValueProtoc.internal_static_com_adebski_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adebski.KeyValueProtoc.Value.class, com.adebski.KeyValueProtoc.Value.Builder.class);
    }

    public static final int VALUEWRAPPER_FIELD_NUMBER = 1;
    private java.util.List<com.adebski.KeyValueProtoc.ValueWrapper> valueWrapper_;
    /**
     * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.adebski.KeyValueProtoc.ValueWrapper> getValueWrapperList() {
      return valueWrapper_;
    }
    /**
     * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.adebski.KeyValueProtoc.ValueWrapperOrBuilder> 
        getValueWrapperOrBuilderList() {
      return valueWrapper_;
    }
    /**
     * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
     */
    @java.lang.Override
    public int getValueWrapperCount() {
      return valueWrapper_.size();
    }
    /**
     * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
     */
    @java.lang.Override
    public com.adebski.KeyValueProtoc.ValueWrapper getValueWrapper(int index) {
      return valueWrapper_.get(index);
    }
    /**
     * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
     */
    @java.lang.Override
    public com.adebski.KeyValueProtoc.ValueWrapperOrBuilder getValueWrapperOrBuilder(
        int index) {
      return valueWrapper_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < valueWrapper_.size(); i++) {
        output.writeMessage(1, valueWrapper_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < valueWrapper_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, valueWrapper_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adebski.KeyValueProtoc.Value)) {
        return super.equals(obj);
      }
      com.adebski.KeyValueProtoc.Value other = (com.adebski.KeyValueProtoc.Value) obj;

      if (!getValueWrapperList()
          .equals(other.getValueWrapperList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValueWrapperCount() > 0) {
        hash = (37 * hash) + VALUEWRAPPER_FIELD_NUMBER;
        hash = (53 * hash) + getValueWrapperList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adebski.KeyValueProtoc.Value parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.KeyValueProtoc.Value parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.Value parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.KeyValueProtoc.Value parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.Value parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.KeyValueProtoc.Value parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.Value parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.KeyValueProtoc.Value parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.Value parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adebski.KeyValueProtoc.Value parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.Value parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.KeyValueProtoc.Value parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adebski.KeyValueProtoc.Value prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.adebski.Value}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.adebski.Value)
        com.adebski.KeyValueProtoc.ValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adebski.KeyValueProtoc.internal_static_com_adebski_Value_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adebski.KeyValueProtoc.internal_static_com_adebski_Value_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adebski.KeyValueProtoc.Value.class, com.adebski.KeyValueProtoc.Value.Builder.class);
      }

      // Construct using com.adebski.KeyValueProtoc.Value.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getValueWrapperFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (valueWrapperBuilder_ == null) {
          valueWrapper_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          valueWrapperBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adebski.KeyValueProtoc.internal_static_com_adebski_Value_descriptor;
      }

      @java.lang.Override
      public com.adebski.KeyValueProtoc.Value getDefaultInstanceForType() {
        return com.adebski.KeyValueProtoc.Value.getDefaultInstance();
      }

      @java.lang.Override
      public com.adebski.KeyValueProtoc.Value build() {
        com.adebski.KeyValueProtoc.Value result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.adebski.KeyValueProtoc.Value buildPartial() {
        com.adebski.KeyValueProtoc.Value result = new com.adebski.KeyValueProtoc.Value(this);
        int from_bitField0_ = bitField0_;
        if (valueWrapperBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            valueWrapper_ = java.util.Collections.unmodifiableList(valueWrapper_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.valueWrapper_ = valueWrapper_;
        } else {
          result.valueWrapper_ = valueWrapperBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adebski.KeyValueProtoc.Value) {
          return mergeFrom((com.adebski.KeyValueProtoc.Value)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adebski.KeyValueProtoc.Value other) {
        if (other == com.adebski.KeyValueProtoc.Value.getDefaultInstance()) return this;
        if (valueWrapperBuilder_ == null) {
          if (!other.valueWrapper_.isEmpty()) {
            if (valueWrapper_.isEmpty()) {
              valueWrapper_ = other.valueWrapper_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValueWrapperIsMutable();
              valueWrapper_.addAll(other.valueWrapper_);
            }
            onChanged();
          }
        } else {
          if (!other.valueWrapper_.isEmpty()) {
            if (valueWrapperBuilder_.isEmpty()) {
              valueWrapperBuilder_.dispose();
              valueWrapperBuilder_ = null;
              valueWrapper_ = other.valueWrapper_;
              bitField0_ = (bitField0_ & ~0x00000001);
              valueWrapperBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getValueWrapperFieldBuilder() : null;
            } else {
              valueWrapperBuilder_.addAllMessages(other.valueWrapper_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adebski.KeyValueProtoc.Value parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adebski.KeyValueProtoc.Value) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.adebski.KeyValueProtoc.ValueWrapper> valueWrapper_ =
        java.util.Collections.emptyList();
      private void ensureValueWrapperIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          valueWrapper_ = new java.util.ArrayList<com.adebski.KeyValueProtoc.ValueWrapper>(valueWrapper_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.adebski.KeyValueProtoc.ValueWrapper, com.adebski.KeyValueProtoc.ValueWrapper.Builder, com.adebski.KeyValueProtoc.ValueWrapperOrBuilder> valueWrapperBuilder_;

      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public java.util.List<com.adebski.KeyValueProtoc.ValueWrapper> getValueWrapperList() {
        if (valueWrapperBuilder_ == null) {
          return java.util.Collections.unmodifiableList(valueWrapper_);
        } else {
          return valueWrapperBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public int getValueWrapperCount() {
        if (valueWrapperBuilder_ == null) {
          return valueWrapper_.size();
        } else {
          return valueWrapperBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public com.adebski.KeyValueProtoc.ValueWrapper getValueWrapper(int index) {
        if (valueWrapperBuilder_ == null) {
          return valueWrapper_.get(index);
        } else {
          return valueWrapperBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public Builder setValueWrapper(
          int index, com.adebski.KeyValueProtoc.ValueWrapper value) {
        if (valueWrapperBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValueWrapperIsMutable();
          valueWrapper_.set(index, value);
          onChanged();
        } else {
          valueWrapperBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public Builder setValueWrapper(
          int index, com.adebski.KeyValueProtoc.ValueWrapper.Builder builderForValue) {
        if (valueWrapperBuilder_ == null) {
          ensureValueWrapperIsMutable();
          valueWrapper_.set(index, builderForValue.build());
          onChanged();
        } else {
          valueWrapperBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public Builder addValueWrapper(com.adebski.KeyValueProtoc.ValueWrapper value) {
        if (valueWrapperBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValueWrapperIsMutable();
          valueWrapper_.add(value);
          onChanged();
        } else {
          valueWrapperBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public Builder addValueWrapper(
          int index, com.adebski.KeyValueProtoc.ValueWrapper value) {
        if (valueWrapperBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValueWrapperIsMutable();
          valueWrapper_.add(index, value);
          onChanged();
        } else {
          valueWrapperBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public Builder addValueWrapper(
          com.adebski.KeyValueProtoc.ValueWrapper.Builder builderForValue) {
        if (valueWrapperBuilder_ == null) {
          ensureValueWrapperIsMutable();
          valueWrapper_.add(builderForValue.build());
          onChanged();
        } else {
          valueWrapperBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public Builder addValueWrapper(
          int index, com.adebski.KeyValueProtoc.ValueWrapper.Builder builderForValue) {
        if (valueWrapperBuilder_ == null) {
          ensureValueWrapperIsMutable();
          valueWrapper_.add(index, builderForValue.build());
          onChanged();
        } else {
          valueWrapperBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public Builder addAllValueWrapper(
          java.lang.Iterable<? extends com.adebski.KeyValueProtoc.ValueWrapper> values) {
        if (valueWrapperBuilder_ == null) {
          ensureValueWrapperIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, valueWrapper_);
          onChanged();
        } else {
          valueWrapperBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public Builder clearValueWrapper() {
        if (valueWrapperBuilder_ == null) {
          valueWrapper_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          valueWrapperBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public Builder removeValueWrapper(int index) {
        if (valueWrapperBuilder_ == null) {
          ensureValueWrapperIsMutable();
          valueWrapper_.remove(index);
          onChanged();
        } else {
          valueWrapperBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public com.adebski.KeyValueProtoc.ValueWrapper.Builder getValueWrapperBuilder(
          int index) {
        return getValueWrapperFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public com.adebski.KeyValueProtoc.ValueWrapperOrBuilder getValueWrapperOrBuilder(
          int index) {
        if (valueWrapperBuilder_ == null) {
          return valueWrapper_.get(index);  } else {
          return valueWrapperBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public java.util.List<? extends com.adebski.KeyValueProtoc.ValueWrapperOrBuilder> 
           getValueWrapperOrBuilderList() {
        if (valueWrapperBuilder_ != null) {
          return valueWrapperBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(valueWrapper_);
        }
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public com.adebski.KeyValueProtoc.ValueWrapper.Builder addValueWrapperBuilder() {
        return getValueWrapperFieldBuilder().addBuilder(
            com.adebski.KeyValueProtoc.ValueWrapper.getDefaultInstance());
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public com.adebski.KeyValueProtoc.ValueWrapper.Builder addValueWrapperBuilder(
          int index) {
        return getValueWrapperFieldBuilder().addBuilder(
            index, com.adebski.KeyValueProtoc.ValueWrapper.getDefaultInstance());
      }
      /**
       * <code>repeated .com.adebski.ValueWrapper valueWrapper = 1;</code>
       */
      public java.util.List<com.adebski.KeyValueProtoc.ValueWrapper.Builder> 
           getValueWrapperBuilderList() {
        return getValueWrapperFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.adebski.KeyValueProtoc.ValueWrapper, com.adebski.KeyValueProtoc.ValueWrapper.Builder, com.adebski.KeyValueProtoc.ValueWrapperOrBuilder> 
          getValueWrapperFieldBuilder() {
        if (valueWrapperBuilder_ == null) {
          valueWrapperBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.adebski.KeyValueProtoc.ValueWrapper, com.adebski.KeyValueProtoc.ValueWrapper.Builder, com.adebski.KeyValueProtoc.ValueWrapperOrBuilder>(
                  valueWrapper_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          valueWrapper_ = null;
        }
        return valueWrapperBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.adebski.Value)
    }

    // @@protoc_insertion_point(class_scope:com.adebski.Value)
    private static final com.adebski.KeyValueProtoc.Value DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adebski.KeyValueProtoc.Value();
    }

    public static com.adebski.KeyValueProtoc.Value getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Value>
        PARSER = new com.google.protobuf.AbstractParser<Value>() {
      @java.lang.Override
      public Value parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Value(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Value> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Value> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.adebski.KeyValueProtoc.Value getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GenericConfigurationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.adebski.GenericConfiguration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
     */
    int getConfigurationCount();
    /**
     * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
     */
    boolean containsConfiguration(
        java.lang.String key);
    /**
     * Use {@link #getConfigurationMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value>
    getConfiguration();
    /**
     * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
     */
    java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value>
    getConfigurationMap();
    /**
     * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
     */

    com.adebski.KeyValueProtoc.Value getConfigurationOrDefault(
        java.lang.String key,
        com.adebski.KeyValueProtoc.Value defaultValue);
    /**
     * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
     */

    com.adebski.KeyValueProtoc.Value getConfigurationOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.adebski.GenericConfiguration}
   */
  public static final class GenericConfiguration extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.adebski.GenericConfiguration)
      GenericConfigurationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenericConfiguration.newBuilder() to construct.
    private GenericConfiguration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenericConfiguration() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GenericConfiguration();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GenericConfiguration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                configuration_ = com.google.protobuf.MapField.newMapField(
                    ConfigurationDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.adebski.KeyValueProtoc.Value>
              configuration__ = input.readMessage(
                  ConfigurationDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              configuration_.getMutableMap().put(
                  configuration__.getKey(), configuration__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adebski.KeyValueProtoc.internal_static_com_adebski_GenericConfiguration_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetConfiguration();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adebski.KeyValueProtoc.internal_static_com_adebski_GenericConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adebski.KeyValueProtoc.GenericConfiguration.class, com.adebski.KeyValueProtoc.GenericConfiguration.Builder.class);
    }

    public static final int CONFIGURATION_FIELD_NUMBER = 1;
    private static final class ConfigurationDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.adebski.KeyValueProtoc.Value> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.adebski.KeyValueProtoc.Value>newDefaultInstance(
                  com.adebski.KeyValueProtoc.internal_static_com_adebski_GenericConfiguration_ConfigurationEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.adebski.KeyValueProtoc.Value.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.adebski.KeyValueProtoc.Value> configuration_;
    private com.google.protobuf.MapField<java.lang.String, com.adebski.KeyValueProtoc.Value>
    internalGetConfiguration() {
      if (configuration_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ConfigurationDefaultEntryHolder.defaultEntry);
      }
      return configuration_;
    }

    public int getConfigurationCount() {
      return internalGetConfiguration().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
     */

    @java.lang.Override
    public boolean containsConfiguration(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetConfiguration().getMap().containsKey(key);
    }
    /**
     * Use {@link #getConfigurationMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value> getConfiguration() {
      return getConfigurationMap();
    }
    /**
     * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value> getConfigurationMap() {
      return internalGetConfiguration().getMap();
    }
    /**
     * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
     */
    @java.lang.Override

    public com.adebski.KeyValueProtoc.Value getConfigurationOrDefault(
        java.lang.String key,
        com.adebski.KeyValueProtoc.Value defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value> map =
          internalGetConfiguration().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
     */
    @java.lang.Override

    public com.adebski.KeyValueProtoc.Value getConfigurationOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value> map =
          internalGetConfiguration().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetConfiguration(),
          ConfigurationDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.adebski.KeyValueProtoc.Value> entry
           : internalGetConfiguration().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.adebski.KeyValueProtoc.Value>
        configuration__ = ConfigurationDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, configuration__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adebski.KeyValueProtoc.GenericConfiguration)) {
        return super.equals(obj);
      }
      com.adebski.KeyValueProtoc.GenericConfiguration other = (com.adebski.KeyValueProtoc.GenericConfiguration) obj;

      if (!internalGetConfiguration().equals(
          other.internalGetConfiguration())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetConfiguration().getMap().isEmpty()) {
        hash = (37 * hash) + CONFIGURATION_FIELD_NUMBER;
        hash = (53 * hash) + internalGetConfiguration().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adebski.KeyValueProtoc.GenericConfiguration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.KeyValueProtoc.GenericConfiguration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.GenericConfiguration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.KeyValueProtoc.GenericConfiguration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.GenericConfiguration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adebski.KeyValueProtoc.GenericConfiguration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.GenericConfiguration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.KeyValueProtoc.GenericConfiguration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.GenericConfiguration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adebski.KeyValueProtoc.GenericConfiguration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adebski.KeyValueProtoc.GenericConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adebski.KeyValueProtoc.GenericConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adebski.KeyValueProtoc.GenericConfiguration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.adebski.GenericConfiguration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.adebski.GenericConfiguration)
        com.adebski.KeyValueProtoc.GenericConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adebski.KeyValueProtoc.internal_static_com_adebski_GenericConfiguration_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetConfiguration();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableConfiguration();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adebski.KeyValueProtoc.internal_static_com_adebski_GenericConfiguration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adebski.KeyValueProtoc.GenericConfiguration.class, com.adebski.KeyValueProtoc.GenericConfiguration.Builder.class);
      }

      // Construct using com.adebski.KeyValueProtoc.GenericConfiguration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableConfiguration().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adebski.KeyValueProtoc.internal_static_com_adebski_GenericConfiguration_descriptor;
      }

      @java.lang.Override
      public com.adebski.KeyValueProtoc.GenericConfiguration getDefaultInstanceForType() {
        return com.adebski.KeyValueProtoc.GenericConfiguration.getDefaultInstance();
      }

      @java.lang.Override
      public com.adebski.KeyValueProtoc.GenericConfiguration build() {
        com.adebski.KeyValueProtoc.GenericConfiguration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.adebski.KeyValueProtoc.GenericConfiguration buildPartial() {
        com.adebski.KeyValueProtoc.GenericConfiguration result = new com.adebski.KeyValueProtoc.GenericConfiguration(this);
        int from_bitField0_ = bitField0_;
        result.configuration_ = internalGetConfiguration();
        result.configuration_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adebski.KeyValueProtoc.GenericConfiguration) {
          return mergeFrom((com.adebski.KeyValueProtoc.GenericConfiguration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adebski.KeyValueProtoc.GenericConfiguration other) {
        if (other == com.adebski.KeyValueProtoc.GenericConfiguration.getDefaultInstance()) return this;
        internalGetMutableConfiguration().mergeFrom(
            other.internalGetConfiguration());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adebski.KeyValueProtoc.GenericConfiguration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adebski.KeyValueProtoc.GenericConfiguration) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.adebski.KeyValueProtoc.Value> configuration_;
      private com.google.protobuf.MapField<java.lang.String, com.adebski.KeyValueProtoc.Value>
      internalGetConfiguration() {
        if (configuration_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ConfigurationDefaultEntryHolder.defaultEntry);
        }
        return configuration_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.adebski.KeyValueProtoc.Value>
      internalGetMutableConfiguration() {
        onChanged();;
        if (configuration_ == null) {
          configuration_ = com.google.protobuf.MapField.newMapField(
              ConfigurationDefaultEntryHolder.defaultEntry);
        }
        if (!configuration_.isMutable()) {
          configuration_ = configuration_.copy();
        }
        return configuration_;
      }

      public int getConfigurationCount() {
        return internalGetConfiguration().getMap().size();
      }
      /**
       * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
       */

      @java.lang.Override
      public boolean containsConfiguration(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetConfiguration().getMap().containsKey(key);
      }
      /**
       * Use {@link #getConfigurationMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value> getConfiguration() {
        return getConfigurationMap();
      }
      /**
       * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value> getConfigurationMap() {
        return internalGetConfiguration().getMap();
      }
      /**
       * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
       */
      @java.lang.Override

      public com.adebski.KeyValueProtoc.Value getConfigurationOrDefault(
          java.lang.String key,
          com.adebski.KeyValueProtoc.Value defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value> map =
            internalGetConfiguration().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
       */
      @java.lang.Override

      public com.adebski.KeyValueProtoc.Value getConfigurationOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value> map =
            internalGetConfiguration().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearConfiguration() {
        internalGetMutableConfiguration().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
       */

      public Builder removeConfiguration(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableConfiguration().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value>
      getMutableConfiguration() {
        return internalGetMutableConfiguration().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
       */
      public Builder putConfiguration(
          java.lang.String key,
          com.adebski.KeyValueProtoc.Value value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableConfiguration().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.adebski.Value&gt; configuration = 1;</code>
       */

      public Builder putAllConfiguration(
          java.util.Map<java.lang.String, com.adebski.KeyValueProtoc.Value> values) {
        internalGetMutableConfiguration().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.adebski.GenericConfiguration)
    }

    // @@protoc_insertion_point(class_scope:com.adebski.GenericConfiguration)
    private static final com.adebski.KeyValueProtoc.GenericConfiguration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adebski.KeyValueProtoc.GenericConfiguration();
    }

    public static com.adebski.KeyValueProtoc.GenericConfiguration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenericConfiguration>
        PARSER = new com.google.protobuf.AbstractParser<GenericConfiguration>() {
      @java.lang.Override
      public GenericConfiguration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GenericConfiguration(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenericConfiguration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenericConfiguration> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.adebski.KeyValueProtoc.GenericConfiguration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adebski_ValueWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adebski_ValueWrapper_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adebski_Value_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adebski_Value_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adebski_GenericConfiguration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adebski_GenericConfiguration_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adebski_GenericConfiguration_ConfigurationEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adebski_GenericConfiguration_ConfigurationEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020key-value.protoc\022\013com.adebski\"\237\001\n\014Valu" +
      "eWrapper\022\025\n\013stringValue\030\001 \001(\tH\000\022\022\n\010intVa" +
      "lue\030\002 \001(\005H\000\022\023\n\tboolValue\030\003 \001(\010H\000\022@\n\023nest" +
      "edConfiguration\030\004 \001(\0132!.com.adebski.Gene" +
      "ricConfigurationH\000B\r\n\013value_oneof\"8\n\005Val" +
      "ue\022/\n\014valueWrapper\030\001 \003(\0132\031.com.adebski.V" +
      "alueWrapper\"\255\001\n\024GenericConfiguration\022K\n\r" +
      "configuration\030\001 \003(\01324.com.adebski.Generi" +
      "cConfiguration.ConfigurationEntry\032H\n\022Con" +
      "figurationEntry\022\013\n\003key\030\001 \001(\t\022!\n\005value\030\002 " +
      "\001(\0132\022.com.adebski.Value:\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_adebski_ValueWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_adebski_ValueWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adebski_ValueWrapper_descriptor,
        new java.lang.String[] { "StringValue", "IntValue", "BoolValue", "NestedConfiguration", "ValueOneof", });
    internal_static_com_adebski_Value_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_adebski_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adebski_Value_descriptor,
        new java.lang.String[] { "ValueWrapper", });
    internal_static_com_adebski_GenericConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_adebski_GenericConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adebski_GenericConfiguration_descriptor,
        new java.lang.String[] { "Configuration", });
    internal_static_com_adebski_GenericConfiguration_ConfigurationEntry_descriptor =
      internal_static_com_adebski_GenericConfiguration_descriptor.getNestedTypes().get(0);
    internal_static_com_adebski_GenericConfiguration_ConfigurationEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adebski_GenericConfiguration_ConfigurationEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
